//
//  DocumentSearchPresenter.swift
//  Particle-Box
//
//  Created by Ian on 4/4/18.
//  Copyright (c) 2018 jumplabs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DocumentSearchPresenterInput
{

}

protocol DocumentSearchPresenterOutput: class
{

}

class DocumentSearchPresenter: DocumentSearchPresenterInput
{
    weak var output: DocumentSearchPresenterOutput!
    
    // MARK: Presentation logic
    

}
