//
//  DocumentSearchConfigurator.swift
//  Particle-Box
//
//  Created by Ian on 4/4/18.
//  Copyright (c) 2018 jumplabs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension DocumentSearchViewController: DocumentSearchPresenterOutput
{

}

extension DocumentSearchInteractor: DocumentSearchViewControllerOutput
{
}

extension DocumentSearchPresenter: DocumentSearchInteractorOutput
{
}

class DocumentSearchConfigurator
{
    // MARK: Object lifecycle
    
    static let sharedInstance = DocumentSearchConfigurator()
    
    // MARK: Configuration
    
    func configure(viewController: DocumentSearchViewController)
    {
        let router = DocumentSearchRouter()
        router.viewController = viewController
        
        let presenter = DocumentSearchPresenter()
        presenter.output = viewController
        
        let interactor = DocumentSearchInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
