//
//  DocumentSearchInteractor.swift
//  Particle-Box
//
//  Created by Ian on 4/4/18.
//  Copyright (c) 2018 jumplabs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DocumentSearchInteractorInput
{
    func getDocuments(filter: BoxDocumentSearchFilter)
}

protocol DocumentSearchInteractorOutput
{
    func updateDataSource(documents: [BoxDocument])
    func createAlert(_ message: String)
}

class DocumentSearchInteractor: DocumentSearchInteractorInput
{
    
    var output: DocumentSearchInteractorOutput!
    var worker = DocumentSearchWorker()
    
        
    // MARK: Business logic
    
    func getDocuments(filter: BoxDocumentSearchFilter) {
        BoxAPIService().getDocuments(filter: filter) { (documents, error) in
            guard error == nil else {
                self.output.createAlert((error?.localizedDescription)!)
                return
            }
            
            if documents != nil {
                self.output.updateDataSource(documents: documents!)
            }
        }
    }

}
