//
//  DocumentSearchInteractor.swift
//  Particle-Box
//
//  Created by Ian on 4/4/18.
//  Copyright (c) 2018 jumplabs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DocumentSearchInteractorInput
{
    func getDocuments(scope: BoxDocumentScope, deviceId: String?, productId: Int?, filter: String?, page: Int?, perPage: Int?)
    
    
}

protocol DocumentSearchInteractorOutput
{
    func updateDataSource(documents: [BoxDocument])
}

class DocumentSearchInteractor: DocumentSearchInteractorInput
{
    
    var output: DocumentSearchInteractorOutput!
    var worker = DocumentSearchWorker()
    
        
    // MARK: Business logic
    
    func getDocuments(scope: BoxDocumentScope, deviceId: String?, productId: Int?, filter: String?, page: Int?, perPage: Int?) {
        BoxAPIService().getDocuments(scope: scope, deviceId: deviceId, productId: productId, filter: filter, page: page) { (documents, error) in
            if documents != nil {
                self.output.updateDataSource(documents: documents!)
            }
        }
    }

}
