//
//  DocumentSearchViewController.swift
//  Particle-Box
//
//  Created by Ian on 4/4/18.
//  Copyright (c) 2018 jumplabs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import SwiftSpinner

protocol DocumentSearchViewControllerInput
{
    func presentNewDocuments(documents: [BoxDocument])
    func presentAlert(_ alert: UIAlertController)
}

protocol DocumentSearchViewControllerOutput
{
    func getDocuments(filter: BoxDocumentSearchFilter)
    func getDocument(key: String, filter: BoxDocumentSearchFilter)
}

class DocumentSearchViewController: UIViewController, DocumentSearchViewControllerInput, UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate
{
    
    var output: DocumentSearchViewControllerOutput!
    var router: DocumentSearchRouter!
    
    var documents = [BoxDocument]()
    var filteredDocuments = [BoxDocument]()
    var searchFilter = BoxDocumentSearchFilter()
    
    // MARK: Interface builder elements
    
    @IBOutlet weak var searchBar: UISearchBar!
    @IBOutlet weak var tableView: UITableView!
    
    static func storyboardInstance() -> DocumentSearchViewController? {
        let storyboard = UIStoryboard(name: String(describing: self),
                                      bundle: nil)
        return storyboard.instantiateInitialViewController() as? DocumentSearchViewController
    }
    
    
    // MARK: Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        DocumentSearchConfigurator.sharedInstance.configure(viewController: self)
    }
    
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.title = "Documents"
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
        self.performSearch()
    }
    
    // MARK: tableView datasource
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.filteredDocuments.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "Cell")
        let doc = filteredDocuments[indexPath.row]
        cell?.textLabel?.text = doc.key
        cell?.detailTextLabel?.text = doc.value
        return cell!
    }

    
    // MARK: tableView delegate
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
    }
    
    
    // MARK: searchBar delegate

    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        if !(searchBar.text?.isEmpty)! {
            self.performSearch()
        }
    }
    
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        // filter the already downloaded documents for matching key before sending request
        if searchText.isEmpty {
            filteredDocuments = documents
        } else {
            filteredDocuments = documents.filter { $0.key.lowercased().contains(searchText.lowercased()) }
        }
        DispatchQueue.main.async {
            self.tableView.reloadData()
        }
    }
    

    // MARK: Event handling
    
    @IBAction func filterPressed(_ sender: Any) {
        router.showSearchFilter()
    }
    
    func performSearch() {
        if (searchBar.text?.isEmpty)! {
            output.getDocuments(filter: searchFilter)
        } else {
            output.getDocument(key: searchBar.text!, filter: searchFilter)
        }
        SwiftSpinner.show("Retrieving documents...")
    }
    
    // MARK: View updates
    
    func presentNewDocuments(documents: [BoxDocument]) {
        SwiftSpinner.hide()
        self.documents = documents
        self.filteredDocuments = documents
        DispatchQueue.main.async {
            self.tableView.reloadData()
        }
    }
    
    func presentAlert(_ alert: UIAlertController) {
        SwiftSpinner.hide()
        self.present(alert, animated: true, completion: nil)
    }


}
