//
//  CreateDocumentPresenter.swift
//  Particle-Box
//
//  Created by Ian on 4/8/18.
//  Copyright (c) 2018 jumplabs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CreateDocumentPresenterInput
{
    func createAlert(_ message: String)
    func documentCreated(_ message: String)
}

protocol CreateDocumentPresenterOutput: class
{
    func presentAlert(_ alert: UIAlertController)
    func documentCreated(_ alert: UIAlertController)
}

class CreateDocumentPresenter: CreateDocumentPresenterInput
{
    weak var output: CreateDocumentPresenterOutput!
    
    // MARK: Presentation logic
    
    func createAlert(_ message: String) {
        let alert = UIAlertController(title: "Error", message: message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "Okay", style: .default, handler: nil))
        output.presentAlert(alert)
    }
    
    func documentCreated(_ message: String) {
        let alert = UIAlertController(title: "Success", message: message, preferredStyle: .alert)
        output.documentCreated(alert)
    }

}
