//
//  CreateDocumentInteractor.swift
//  Particle-Box
//
//  Created by Ian on 4/8/18.
//  Copyright (c) 2018 jumplabs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CreateDocumentInteractorInput
{
    func createDocument(document: BoxDocument)
}

protocol CreateDocumentInteractorOutput
{
    func documentCreated(_ message: String)
    func createAlert(_ message: String)
}

class CreateDocumentInteractor: CreateDocumentInteractorInput
{
    var output: CreateDocumentInteractorOutput!    
        
    // MARK: Business logic
    
    func createDocument(document: BoxDocument) {
        if isDocumentDataValid(document: document) {
            BoxAPIService.shared.createDocument(document: document) { (responseCode, error) in
                guard error == nil else {
                    self.output.createAlert((error?.localizedDescription)!)
                    return
                }
                
                if responseCode != nil {
                    switch responseCode {
                    case 201?:
                        self.output.documentCreated("Document created!")
                        break
                    case 400?:
                        self.output.createAlert("Invalid input, object invalid.")
                        break
                    default:
                        break
                    }
                }
            }
        }
    }
    
    func isDocumentDataValid(document: BoxDocument) -> Bool {
        if document.key.isEmpty {
            output.createAlert("Please enter a key.")
            return false
        }
        else if document.value.isEmpty {
            output.createAlert("Please enter a value.")
            return false
        }
        else if document.deviceId.isEmpty {
            output.createAlert("Please enter a device id.")
            return false
        }
        else if document.productId == 0 {
            output.createAlert("Please enter a product id.")
            return false
        }
        else {
            return true
        }
    }
}
