//
//  DocumentSearchInteractor.swift
//  Particle-Box
//
//  Created by Ian on 4/4/18.
//  Copyright (c) 2018 jumplabs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DocumentSearchInteractorInput
{

}

protocol DocumentSearchInteractorOutput
{

}

class DocumentSearchInteractor: DocumentSearchInteractorInput
{
    var output: DocumentSearchInteractorOutput!
    var worker = DocumentSearchInteractorWorker()
    
        
    // MARK: Business logic
    

}
