//
//  DocumentSearchFilterConfigurator.swift
//  Particle-Box
//
//  Created by Ian on 4/8/18.
//  Copyright (c) 2018 jumplabs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension DocumentSearchFilterViewController: DocumentSearchFilterPresenterOutput
{

}

extension DocumentSearchFilterInteractor: DocumentSearchFilterViewControllerOutput
{
}

extension DocumentSearchFilterPresenter: DocumentSearchFilterInteractorOutput
{
}

class DocumentSearchFilterConfigurator
{
    // MARK: Object lifecycle
    
    static let sharedInstance = DocumentSearchFilterConfigurator()
    
    // MARK: Configuration
    
    func configure(viewController: DocumentSearchFilterViewController)
    {
        let router = DocumentSearchFilterRouter()
        router.viewController = viewController
        
        let presenter = DocumentSearchFilterPresenter()
        presenter.output = viewController
        
        let interactor = DocumentSearchFilterInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
