//
//  DocumentSearchFilterInteractor.swift
//  Particle-Box
//
//  Created by Ian on 4/8/18.
//  Copyright (c) 2018 jumplabs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DocumentSearchFilterInteractorInput
{
    func setPerPage(perPage: Int)
    func setScope(scope: BoxDocumentScope)
}

protocol DocumentSearchFilterInteractorOutput
{
    func setPerPageSegmentedControlIndex(_ index: Int)
    func setScopeSegmentedControlIndex(_ index: Int)
}

class DocumentSearchFilterInteractor: DocumentSearchFilterInteractorInput
{
    var output: DocumentSearchFilterInteractorOutput!
    var worker = DocumentSearchFilterWorker()
    
        
    // MARK: Business logic
    
    func setPerPage(perPage: Int) {
        switch perPage {
        case 10:
            output.setPerPageSegmentedControlIndex(0)
            break
        case 25:
            output.setPerPageSegmentedControlIndex(1)
            break
        case 50:
            output.setPerPageSegmentedControlIndex(2)
            break
        case 100:
            output.setPerPageSegmentedControlIndex(3)
            break
        default:
            break
        }
    }
    
    func setScope(scope: BoxDocumentScope) {
        switch scope {
        case .none:
            output.setScopeSegmentedControlIndex(0)
            break
        case .device:
            output.setScopeSegmentedControlIndex(1)
            break
        case .user:
            output.setScopeSegmentedControlIndex(2)
            break
        case .product:
            output.setScopeSegmentedControlIndex(3)
            break
        }
    }

}
