//
//  DocumentSearchFilterPresenter.swift
//  Particle-Box
//
//  Created by Ian on 4/8/18.
//  Copyright (c) 2018 jumplabs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DocumentSearchFilterPresenterInput
{
    func setPerPageSegmentedControlIndex(_ index: Int)
    func setScopeSegmentedControlIndex(_ index: Int)
}

protocol DocumentSearchFilterPresenterOutput: class
{
    func presentPerPageSelection(_ index: Int)
    func presentScopeSelection(_ index: Int)
}

class DocumentSearchFilterPresenter: DocumentSearchFilterPresenterInput
{
    weak var output: DocumentSearchFilterPresenterOutput!
    
    // MARK: Presentation logic
    
    func setPerPageSegmentedControlIndex(_ index: Int) {
        output.presentPerPageSelection(index)
    }
    
    func setScopeSegmentedControlIndex(_ index: Int) {
        output.presentScopeSelection(index)
    }

}
